---
# Complete configuration with all the possible deps
services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes: [.:/app]
    environment: [NODE_ENV=test]
    depends_on: [db, redis]
  db:
    image: postgres:14-alpine
    environment: [POSTGRES_USER=test, POSTGRES_PASSWORD=test]
  redis:
    image: redis:7-alpine
