---
steps:
  # Unit tests - just run the app
  - label: ':nodejs: Unit Tests'
    plugins:
      - docker-compose#v4.14.0:
          run: app
          command: [npm, run, test:unit]
  # Integration tests w/ db
  - label: ':nodejs: :postgresql: Integration Tests'
    commands:
      # Start the db first
      - docker compose up -d db
      # Wait for db to be ready
      - docker compose run --rm app /bin/sh -c "until nc -z db 5432; do sleep 1; done"
    plugins:
      - docker-compose#v4.14.4:
          run: app
          command: [npm, run, test:integration]
  # Cache tests with Redis
  - label: ':nodejs: :redis: Cache Tests'
    commands:
      # Start Redis first
      - docker compose up -d redis
      # Wait for Redis to be ready
      - docker compose run --rm app /bin/bash -c "until nc -z redis 6379; do sleep
        1; done"
    plugins:
      - docker-compose#v4.14.0:
          run: app
          command: [npm, run, test:cache]
