---
# Conf for integration tests - needs a db
services:
  app:
    environment:
      - NODE_ENV=test
      - POSTGRES_HOST=db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    depends_on: [db]
  db:
    image: postgres:14-alpine
    environment: [POSTGRES_USER=test, POSTGRES_PASSWORD=test]
